Profile_Management/Controllers/ActionLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Profile_Management.Models;

namespace Profile_Management.Controllers
{
    public class ActionLogController : Controller
    {
        // GET: ActionLog
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var actionlog = db.actionLogs.OrderByDescending(a => a.ActionLogID).ToList();
            return View(actionlog);
        }
    }
}

Profile_Management/Controllers/MM_NationalityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Antlr.Runtime.Misc;
using Profile_Management.Models;
using Profile_Management.Models.EF;

namespace Profile_Management.Controllers
{
    public class MM_NationalityController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: MM_Nationality
        public ActionResult Index()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
           
            return View();
        }

       
        // GET: MM_Nationality/Create
        public ActionResult Create()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var model = new NationalityViewModel
            {
                NewNationality = new Nationality(),
                Nationalities = db.nationalities.ToList()
            };

            return View(model);
        }

        // POST: MM_Nationality/Create
        [HttpPost]
        public ActionResult Create(NationalityViewModel model)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values
                            .SelectMany(v => v.Errors)
                            .Select(e => e.ErrorMessage)
                            .ToList();

                foreach (var error in errors)
                {
                    System.Diagnostics.Debug.WriteLine(error);
                }

                // Trả lại form nếu có lỗi
                model.Nationalities = db.nationalities.ToList();
                return View(model);
            }

            db.nationalities.Add(model.NewNationality);
            db.SaveChanges();

            return RedirectToAction("Create");
        }

        [HttpPost]
        public JsonResult UpdateNationality(int id, string nationName)
        {
            var nationality = db.nationalities.Find(id);
            if (nationality != null)
            {
                nationality.Nation_Name = nationName;
                db.SaveChanges();
                return Json(new { success = true, message = "保存完了!" });
            }
            return Json(new { success = false, message = "データはなし、エーラー！" });
        }

        [HttpPost]
        public JsonResult DeleteNationality(int id)
        {
            var nationality = db.nationalities.Find(id);
            if (nationality != null)
            {
                db.nationalities.Remove(nationality);
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }




    }
}

Profile_Management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <title>Profile Management</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/Assets_Trial/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="~/Assets_Trial/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/Assets_Trial/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/Assets_Trial/css/style.css" rel="stylesheet">
    <link href="~/Assets_Trial/css/pagination.css" rel="stylesheet" />
    <link href="~/Assets_Trial/css/Highlight.css" rel="stylesheet" />
    <style type="text/css">
        /*Admin label*/
        .admin-label {
            position: absolute;
            top: 0;
            right: 0;
            background-color: #ff0000;
            color: #fff;
            font-size: 7px;
            padding: 2px 5px;
            border-radius: 5px;
            transform: translate(30%, -30%);
        }
        /*Admin label for small monitor*/
        @@media (max-width: 768px) {
            .admin-label {
                right: -30px;
                font-size: 10px;
            }
        }
    </style>

</head>

<body style="padding: @(ViewBag.Padding ?? "100px 50px 50px 50px")">


    <!-- Spinner Start -->
    <div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
        <div class="spinner-grow text-primary" role="status"></div>
    </div>
    <!-- Spinner End -->
    <!-- Navbar start -->
    <div class="container-fluid fixed-top">

        <div class="container px-0">
            <nav class="navbar navbar-light bg-white navbar-expand-xl">
                <a href="@Url.Action("Index", "Home")" class="navbar-brand"><h1 class="text-primary display-6">Profile Management</h1></a>
                <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars text-primary"></span>
                </button>
                <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                    <div class="navbar-nav mx-auto">
                        @*<a href="@Url.Action("Index", "Home")" class="nav-item nav-link active">ホームページ</a>*@
                        <a href="@Url.Action("Create_Profile", "ManagementUser")" class="nav-item nav-link">新規作成</a>
                        <a href="@Url.Action("Index", "ManagementUser")" class="nav-item nav-link">個人管理</a>
                        <a href="@Url.Action("Create", "MM_Nationality")" class="nav-item nav-link">国籍管理</a>
                        @if (Session["Role"] != null && Session["Role"].ToString() == "Admin")
                        {
                            <a href="@Url.Action("Management_Users", "Account")" class="nav-item nav-link position-relative">
                                アカウント管理
                                <span class="admin-label">Admin</span>
                            </a>
                            <a href="@Url.Action("Index","ActionLog")" class="nav-item nav-link position-relative" target="_blank" >
                                Log管理
                                <span class="admin-label">Admin</span>
                            </a>
                        }
                        <a href="@Url.Action("Contact", "Home")" class="nav-item nav-link">情報</a>
                    </div>
                    <div class="d-flex m-3 me-0">
                        @*@using (Html.BeginForm("Index","ManagementUser", FormMethod.Get))
                            {
                                <button name="searchString" class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fas fa-search text-primary"></i></button>
                            }*@

                        <a href="#" class="my-auto">
                            @*<i class="fas fa-user fa-2x"></i>*@
                            @Html.Partial("_LoginPartial")
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->
    <!-- Modal Search Start -->
    <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-fullscreen">
            <div class="modal-content rounded-0">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">検索キー</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body d-flex align-items-center">
                    <div class="input-group w-75 mx-auto d-flex">
                        <input type="search" class="form-control p-3" placeholder="keywords" aria-describedby="search-icon-1">
                        <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal Search End -->
    @RenderBody()
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
        <div class="container py-5">
            <div class="pb-4 mb-4" style="border-bottom: 1px solid rgba(226, 175, 24, 0.5) ;">
                <div class="row g-4">
                    <div class="col-lg-3">
                        <a href="#">
                            <h1 class="text-primary mb-0">...</h1>
                            <p class="text-secondary mb-0">...</p>
                        </a>
                    </div>
                    <div class="col-lg-6">
                        <div class="position-relative mx-auto">
                            <input class="form-control border-0 w-100 py-3 px-4 rounded-pill" type="number" placeholder="Your Email">
                            <button type="submit" class="btn btn-primary border-0 border-secondary py-3 px-4 position-absolute rounded-pill text-white" style="top: 0; right: 0;">Subscribe Now</button>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="d-flex justify-content-end pt-3">
                            <a class="btn  btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-secondary btn-md-square rounded-circle" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <div class="footer-item">
                        <h4 class="text-light mb-3">Why People Like us!</h4>
                        <p class="mb-4">
                            typesetting, remaining essentially unchanged. It was
                            popularised in the 1960s with the like Aldus PageMaker including of Lorem Ipsum.
                        </p>
                        <a href="" class="btn border-secondary py-2 px-4 rounded-pill text-primary">Read More</a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="d-flex flex-column text-start footer-item">
                        <h4 class="text-light mb-3">...</h4>
                        <a class="btn-link" href="">About Us</a>
                        <a class="btn-link" href="">Contact Us</a>
                        <a class="btn-link" href="">Privacy Policy</a>
                        <a class="btn-link" href="">Terms & Condition</a>
                        <a class="btn-link" href="">Return Policy</a>
                        <a class="btn-link" href="">FAQs & Help</a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="d-flex flex-column text-start footer-item">
                        <h4 class="text-light mb-3">Account</h4>
                        <a class="btn-link" href="">My Account</a>
                        <a class="btn-link" href="">...</a>
                        <a class="btn-link" href="">...</a>
                        <a class="btn-link" href="">...</a>
                        <a class="btn-link" href="">...</a>
                        <a class="btn-link" href="">...</a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="footer-item">
                        <h4 class="text-light mb-3">Contact</h4>
                        <p>Address: 1429 Netus Rd, NY 48247</p>
                        <p>Email: Example@gmail.com</p>
                        <p>Phone: +0123 4567 8910</p>
                        <p>Payment Accepted</p>
                        <img src="~/Assets_Trial/img/payment.png" class="img-fluid" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Copyright Start -->
    <div class="container-fluid copyright bg-dark py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    <span class="text-light"><a href="#"><i class="fas fa-copyright text-light me-2"></i>Your Site Name</a>, All right reserved.</span>
                </div>
                <div class="col-md-6 my-auto text-center text-md-end text-white">
                    <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->
                    <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->
                    <!--/*** you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". ***/-->
                    Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a> Distributed By <a class="border-bottom" href="https://themewagon.com">ThemeWagon</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Copyright End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>
    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Assets_Trial/lib/easing/easing.min.js"></script>
    <script src="~/Assets_Trial/lib/waypoints/waypoints.min.js"></script>
    <script src="~/Assets_Trial/lib/lightbox/js/lightbox.min.js"></script>
    <script src="~/Assets_Trial/lib/owlcarousel/owl.carousel.min.js"></script>
    @*<script src="~/Scripts/jquery-3.7.0.min.js"></script>*@

    <!-- Template Javascript -->
    <script src="~/Assets_Trial/js/main.js"></script>
    @RenderSection("scripts", required: false)
</body>

</html>